version: '3.8'

services:
  db:
    build: ./database
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: grepmind
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build: ./backend
    container_name: backend
    network_mode: host
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: grepmind
      JWT_SECRET: ec846f9100f102b76ab9d31eb2d02c98b2aefa24e3fcb24784b9fdf4fb9a75c7fe361a3e6b12eb01d6eab38498b1d06cd6c761642dcdbd2b76e433179d761cb6
      FRONTEND_URL: http://localhost:3000
      DATABASE_URL: postgres://admin:admin123@localhost:5432/grepmind
    depends_on:
      - db
      

  frontend:
    build: ./frontend
    container_name: frontend
    network_mode: host     
    environment:
      - REACT_APP_API_URL=http://localhost:5000    
    ports:
      - "3000:80"
    depends_on:
      - backend
       

volumes:
  postgres_data:
   
