version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  db:
    build: ./database
    container_name: db_service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: grepmind
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network      


  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: grepmind
      NODE_ENV: development
      JWT_SECRET: ec846f9100f102b76ab9d31eb2d02c98b2aefa24e3fcb24784b9fdf4fb9a75c7fe361a3e6b12eb01d6eab38498b1d06cd6c761642dcdbd2b76e433179d761cb6
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - db
    networks:
      - app_network       
      

  frontend:
    build: ./frontend
    container_name: frontend_service  
    environment:
      REACT_APP_API_URL: http://localhost:5000    
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network       
       

volumes:
  postgres_data:
   
